apiVersion: v1
kind: ConfigMap
metadata:
  name: DevOpsCap-AWSAuth
  namespace: default
data:
  mapRoles: |
    - rolearn: arn:aws:iam::568283627415:role/DevOpsCap-Nodes-NodeInstanceRole-1SDCDDQS25ED6
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes