apiVersion: v1
kind: Service
metadata:
  name: blue-green-loadbalancer
  labels:
    app: blue-green-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31910
  selector:
    app: blue
