apiVersion: v1
kind: Service
metadata:
  name: blue-loadbalancer
  labels:
    app: blue
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: blue
