apiVersion: v1
kind: Service
metadata:
  name: green-loadbalancer
  labels:
    app: green
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: green
